src/Isen.DotNet.Web/Models/ErrorViewModel.cs
using System;

namespace Isen.DotNet.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Isen.DotNet.Web/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Isen.DotNet.Web.Controllers
{
    public abstract class BaseController<T, TRepo> : Controller
        where T : BaseModel<T>
        where TRepo : IBaseRepository<T>
    {
        #region Membres et constructeur

        protected readonly TRepo Repository;

        protected BaseController(TRepo repository)
        {
            Repository = repository;
        }

        #endregion

        #region Actions MVC

        public virtual IActionResult Index() => View(Repository.GetAll());

        [HttpGet] // facultatif car par défaut
        public virtual IActionResult Edit(int? id)
        {
            if (id == null) return View();
            return View(Repository.Single(id.Value));
        }

        [HttpPost]
        public virtual IActionResult Edit(int id, [Bind] T model)
        {
            Repository.Update(model);
            Repository.SaveChanges();
            return RedirectToAction("Index");
        }

        public virtual IActionResult Delete(int? id)
        {
            if (id != null)
            {
                Repository.Delete(id.Value);
                Repository.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        #endregion

        #region API

        [HttpGet]
        [Route("api/[controller]/status")]
        public virtual JsonResult Status()
        {
            dynamic result = new ExpandoObject();
            result.serverTime = DateTime.Now;
            result.controller = typeof(T).Name;
            return Json(result);
        }

        [HttpGet]
        [Route("api/[controller]/{id}")]
        public virtual JsonResult GetById(int id)
        {
            var entity = Repository.Single(id);
            if (entity == null) return Json(new {});
            return Json(entity.ToDynamic());
        }

        [HttpGet]
        [Route("api/[controller]")]
        public virtual JsonResult GetAll()
        {
            var all = Repository
                .GetAll()
                .Select(e => e.ToDynamic())
                .ToList();
            return Json(all);
        }

        #endregion
    }
}

src/Isen.DotNet.Web/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;

namespace Isen.DotNet.Web.Controllers
{
    public class ClubController : BaseController<Club, IClubRepository>
    {
        public ClubController(IClubRepository repository) : base(repository)
        {
        }
    }
}

src/Isen.DotNet.Web/Controllers/HistoricController.cs
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Isen.DotNet.Web.Controllers
{
    public class HistoricController : BaseController<Historic, IHistoricRepository>
    {
        public HistoricController(IHistoricRepository repository) : base(repository)
        {
        }
    }
}

src/Isen.DotNet.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;

namespace Isen.DotNet.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Isen.DotNet.Web/Controllers/PlayerController.cs
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Isen.DotNet.Web.Controllers
{
    public class PlayerController : BaseController<Player, IPlayerRepository>
    {
        public PlayerController(IPlayerRepository repository) : base(repository)
        {
        }
    }
}

src/Isen.DotNet.Web/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Isen.DotNet.Library.Models;
using Isen.DotNet.Library.Context;

namespace Isen.DotNet.Web.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TodoController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public TodoController(ApplicationDbContext context)
        {
            _context = context;
        }

        
        [HttpGet("{id}")]
        public async Task<ActionResult<Club>> GetTodoItem(int id)
        {
            var todoItem = await _context.ClubCollection.FindAsync(id);

            if (todoItem == null)
            {
                return NotFound();
            }

            return todoItem;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<Club>>> GetTodoItems()
        {
            return await _context.ClubCollection.ToListAsync();
        }

        [HttpPost]
        public async Task<ActionResult<Club>> PostTodoItem(Club item)
        {
            _context.ClubCollection.Add(item);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(GetTodoItem), new { id = item.Id }, item);
        }
    }
}

src/Isen.DotNet.Web/Views/Club/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'un club";
}
@using Isen.DotNet.Library.Models
@model Club
<h1>Edition d'un club (formulaire)</h1>

<div class="row">
    <div class="col-12">
        
        <form class="form-group" asp-action="Edit">
            
            <input type="hidden" 
                   asp-for="Id"
                   value="@Model?.Id" />

            <div class="form-group">
                <label for="clubName">Nom du club</label>
                <input id="clubName"
                       type="text"
                       class="form-control"
                       placeholder="Club name"
                       asp-for="Name"
                       value="@Model?.Name" />
            </div>

            <div class="form-group">
                <label for="clubAddress">Adress du club</label>
                <input id="clubAddress"
                       type="text"
                       class="form-control"
                       placeholder="Club address"
                       asp-for="address"
                       value="@Model?.address" />
            </div>

            <button type="submit" class="btn btn-primary">Valider</button>
            <a class="btn btn-secondary"
               asp-controller="Club" asp-action="Index">Annuler</a>

        </form>

    </div>
</div>

src/Isen.DotNet.Web/Views/Club/Index.cshtml
@{
    ViewData["Title"] = "Tous les clubs";
}
@using Isen.DotNet.Library.Models
@model IEnumerable<Club>

<h1>Tous les clubs</h1>

<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Id</th>
          <th scope="col">Nom</th>
          <th scope="col">Adresse</th>
          <th scope="col">logo</th>
          <th>Action...</th>
      </tr>
  </thead>
  <tbody>
    @foreach(var club in Model)
    { 
      <tr>
          <th scope="row">@club.Id</th>
          <td>@club.Name</td>
          <td>@club.address</td>
          <td>
              <img width="50" height="50" src=@club.logo ><img>
          </td>
          <td>
              <a class="btn btn-outline-primary"
                 asp-controller="Club"
                 asp-action="Edit"
                 asp-route-id="@club.Id">Modifier</a>
              <a class="btn btn-outline-danger"
                 asp-controller="Club"
                 asp-action="Delete"
                 asp-route-id="@club.Id">Supprimer</a>
          </td>
      </tr>
     }
  </tbody>
</table>

src/Isen.DotNet.Web/Views/Historic/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'un contrat";
}
@using Isen.DotNet.Library.Models
@using Isen.DotNet.Library.Repositories.Interfaces
@model Historic
@inject IPlayerRepository _playerRepository
@inject IClubRepository _clubRepository
<h1>Edition d'un contrat</h1>

<div class="row">
    <div class="col-12">
        
        <form class="form-group" asp-action="Edit">

            <input type="hidden"
                   asp-for="Id"
                   value="@Model?.Id" />
            @{
                var startDateString = Model?.StartDate
                    .GetValueOrDefault(DateTime.MinValue)
                    .ToString("dd/MM/yyyy");
            }

            <div class="form-group">
                <label for="StartDate">Date de début</label>
                <input id="StartDate"
                       type="text"
                       class="form-control"
                       placeholder="Date de debut"
                       asp-for="StartDate"
                       value="@startDateString" />
            </div>

            @{
                var endDateString = Model?.EndDate
                    .GetValueOrDefault(DateTime.MinValue)
                    .ToString("dd/MM/yyyy");
            }

            <div class="form-group">
                <label for="EndDate">Date de fin</label>
                <input id="EndDate"
                       type="text"
                       class="form-control"
                       placeholder="Date de fin"
                       asp-for="EndDate"
                       value="@endDateString" />
            </div>

            <div class="form-group">
                <label for="HPlayer">Player</label>
                @Html.DropDownListFor(
                    p => p.HPlayerId,
                    new SelectList(
                        _playerRepository.GetAll(),
                        "Id",
                        "Name"),
                    "Sélectionnez une joueuse...",
                    new { @class = "form-control" }
                    )
            </div>

            <div class="form-group">
                <label for="HPlayIn">Club</label>
                @Html.DropDownListFor(
                    // Quel champ du modèle (Person) est concerné
                    p => p.HPlayInId,
                    // Création d'une liste
                    new SelectList(
                        // Données de la liste
                        _clubRepository.GetAll(),
                        // Champ correspondant à l'id
                        "Id",
                        // Champ correspondant au texte affiché
                        "Name"),
                    // Item par défaut
                    "Sélectionnez un club...",
                    // Ckasse CSS
                    new { @class = "form-control" }
                    )
            </div>


            <button type="submit" class="btn btn-primary">Valider</button>
            <a class="btn btn-secondary"
               asp-controller="Historic" asp-action="Index">Annuler</a>

        </form>

    </div>
</div>

src/Isen.DotNet.Web/Views/Historic/Index.cshtml
@{
    ViewData["Title"] = "Tous les historiques";
}
@using Isen.DotNet.Library.Models
@model IEnumerable<Historic>

<h1>Tous les historique</h1>

<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Id</th>
          <th scope="col">Player</th>
          <th scope="col">Club</th>
          <th scope="col">Durée</th>
          <th>Action...</th>
      </tr>
  </thead>
  <tbody>
    @foreach(var histo in Model)
    { 
      <tr>
          <th scope="row">@histo.Id</th>
          <td>@histo.HPlayer.Name</td>
          <td>@histo.HPlayIn.Name</td>
          <td>@histo.Duration an(s)</td>
          <td>
              <a class="btn btn-outline-primary"
                 asp-controller="Historic"
                 asp-action="Edit"
                 asp-route-id="@histo.Id">Modifier</a>
              <a class="btn btn-outline-danger"
                 asp-controller="Historic"
                 asp-action="Delete"
                 asp-route-id="@histo.Id">Supprimer</a>
          </td>
      </tr>
     }
  </tbody>
</table>

src/Isen.DotNet.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Isen.DotNet.Web/Views/Player/Edit.cshtml
@{
    ViewData["Title"] = "Edition d'une joueuse";
}
@using Isen.DotNet.Library.Models
@model Player
<h1>Edition d'une joueuse (formulaire)</h1>

<div class="row">
    <div class="col-12">
        
        <form class="form-group" asp-action="Edit">
            
            <input type="hidden" 
                   asp-for="Id"
                   value="@Model?.Id" />

            <div class="form-group">
                <label for="LastName">Nom</label>
                <input id="LastName"
                       type="text"
                       class="form-control"
                       placeholder="Last name"
                       asp-for="LastName"
                       value="@Model?.LastName" />
            </div>

            <div class="form-group">
                <label for="FirstName">Prénom</label>
                <input id="FirstName"
                       type="text"
                       class="form-control"
                       placeholder="First name"
                       asp-for="FirstName"
                       value="@Model?.FirstName" />
            </div>
            
            @{
                var dateString = Model?.DateOfBirth
                    .GetValueOrDefault(DateTime.MinValue)
                    .ToString("dd/MM/yyyy");
            }

            <div class="form-group">
                <label for="DateOfBirth">Date de naissance</label>
                <input id="DateOfBirth"
                       type="text"
                       class="form-control"
                       placeholder="Date de naissance"
                       asp-for="DateOfBirth"
                       value="@dateString" />
            </div>

            <button type="submit" class="btn btn-primary">Valider</button>
            <a class="btn btn-secondary"
               asp-controller="Player" asp-action="Index">Annuler</a>

        </form>

    </div>
</div>

src/Isen.DotNet.Web/Views/Player/Index.cshtml
@{
    ViewData["Title"] = "Toutes les joueuses";
}
@using Isen.DotNet.Library.Models
@using Isen.DotNet.Library.Repositories.Interfaces
@model IEnumerable<Player>
@inject IHistoricRepository _historicRepository

<h1>Toutes les joueuses</h1>

<table class="table table-striped">
  <thead>
      <tr>
          <th scope="col">Id</th>
          <th scope="col">Nom</th>
          <th scope="col">Prénom</th>
          <th scope="col">Date de naissance</th>
          <th scope="col">Age</th>
          <th scope="col">Historique</th>
          <th>Action...</th>
      </tr>
  </thead>
  <tbody>
    @foreach(var player in Model)
    { 
        var dateString = player.DateOfBirth.HasValue ?
            player.DateOfBirth.Value.ToShortDateString() :
            "";

        IEnumerable<Historic> historicRepository = _historicRepository.GetAll();

      <tr>
          <th scope="row">@player.Id</th>
          <td>@player.LastName</td>
          <td>@player.FirstName</td>
          <td>@dateString</td>
          <td>@player.Age an(s)</td>
          <td>
            @foreach (var histo in historicRepository)
            {
                @if(histo.HPlayerId == @player.Id)
                {
                    <p>@histo</p>
                }
            }
          </td>
          <td>
              <a class="btn btn-outline-primary"
                 asp-controller="Player"
                 asp-action="Edit"
                 asp-route-id="@player.Id">Modifier</a>
              <a class="btn btn-outline-danger"
                 asp-controller="Player"
                 asp-action="Delete"
                 asp-route-id="@player.Id">Supprimer</a>
          </td>
      </tr>
     }
  </tbody>
</table>

src/Isen.DotNet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Isen.DotNet.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    Isen<strong>.Net 👍</strong>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                                asp-area="" 
                                asp-controller="Home" 
                                asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                                asp-area="" 
                                asp-controller="Home" 
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle"
                               data-toggle="dropdown"
                               href="#" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Club</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Club" 
                                   asp-action="Index">Toutes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Club" 
                                   asp-route-id=""
                                   asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle"
                               data-toggle="dropdown"
                               href="#" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Joueuses</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Player" 
                                   asp-action="Index">Toutes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Player" 
                                   asp-route-id=""
                                   asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle"
                               data-toggle="dropdown"
                               href="#" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Historique</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Historic" 
                                   asp-action="Index">Toutes</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"
                                   asp-area="" 
                                   asp-controller="Historic" 
                                   asp-route-id=""
                                   asp-action="Edit">Ajouter...</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Isen.DotNet.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>